title:    "Lite App Manifests"
tagline:  "Lite Apps for use with Hermit: https://hermit.chimbori.com/"
url:      "https://chimbori.github.io/lite-apps"
cdn_url:  "https://chimbori.github.io/lite-apps"
include:  [
            "_data"
          ]
exclude:  [
            "*.bat",
            "*.gradle",
            "*.properties",
            "*.sh",
            "blocklists/",
            "build/",
            "Gemfile",
            "Gemfile.lock",
            "gradle/",
            "gradlew",
            "lite-apps/",
            "node_modules/",
            "package.json",
            "src/"
          ]
