title:    "Lite App Manifests"
tagline:  "Lite Apps for use with Hermit: https://hermit.chimbori.com/"
url:      "https://chimbori.github.io/lite-apps/"
cdn_url:
exclude:  [
            "*.bat",
            "*.gradle",
            "*.properties",
            "*.sh",
            "build/",
            "Gemfile",
            "Gemfile.lock",
            "gradle/",
            "gradlew",
            "lite-apps/",
            "src/"
          ]
gems:
  - jekyll-babel  # Processes .jsx files to .js.
